# SPDX-License-Identifier: MIT
---
- name: Assert kdump_target is null or a dictionary
  ansible.builtin.assert:
    that:
      - >-
        (kdump_target is none)
        or (kdump_target is mapping)
    fail_msg: >-
      kdump_target must be null or a dictionary,
      got {{ kdump_target | type_debug }}
  when: kdump_target is defined

- name: Assert kdump_target dict contains only valid keys
  ansible.builtin.assert:
    that:
      - >-
        kdump_target.keys() | list | difference(__kdump_target_valid_keys)
        | length == 0
    fail_msg: >-
      kdump_target contains invalid keys:
      {{ kdump_target.keys() | list | difference(__kdump_target_valid_keys) | join(', ') }}
  vars:
    __kdump_target_valid_keys:
      - type
      - location
  when: kdump_target is mapping

- name: Assert kdump_target.type is set and is a string
  ansible.builtin.assert:
    that:
      - kdump_target.type is defined
      - kdump_target.type is string
    fail_msg: >-
      kdump_target.type must be a string,
      got {{ kdump_target.type | default('undefined') | type_debug }}
  when: kdump_target is mapping

- name: Assert kdump_target.location is a string when set
  ansible.builtin.assert:
    that:
      - kdump_target.location is string
    fail_msg: >-
      kdump_target.location must be a string,
      got {{ kdump_target.location | type_debug }}
  when:
    - kdump_target is mapping
    - kdump_target.location is defined
